server:
  port: ${PORT:8080}

spring:
  application:
    name: usthb-chatbot-backend

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/chatbot_db}
    username: ${DB_USERNAME:chatbot}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# Services externes (URLs publiques)
rasa:
  url: ${RASA_URL:http://0.0.0.0:5005}

llm:
  url: ${LLAMA_URL:http://0.0.0.0:5001}

# Configuration JWT
app:
  jwtSecret: ${JWT_SECRET:mySecretKey}
  jwtExpirationMs: ${JWT_EXPIRATION:86400000}

# Configuration uploads
file:
  upload-dir: ${UPLOAD_DIR:uploads/}
  max-size: ${MAX_FILE_SIZE:10MB}

# Configuration logs
logging:
  level:
    com.chatbot: INFO
    org.springframework.security: DEBUG