server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chatbot
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret: ${JWT_SECRET:your-secret-key-here-must-be-at-least-32-characters}
  expiration: 86400000 # 24 hours

rasa:
  url: ${RASA_URL:http://localhost:5005}
  webhook: /webhooks/rest/webhook
  train: /model/train

llm:
  url: ${LLM_URL:http://localhost:5001}
  process-pdf: /process-pdf
  generate-dataset: /generate-rasa-dataset

logging:
  level:
    root: INFO
    com.usthb: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO 