server:
  port: 5000

spring:
  application:
    name: chatbot-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/chatbot_db
    username: ${DB_USERNAME:chatbot_user}
    password: ${DB_PASSWORD:chatbot_pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:mySecretKey}
  expiration: 86400000 # 24 hours in milliseconds

# External Services
rasa:
  url: http://localhost:5005

llama:
  url: http://localhost:5001

  webhook-url: ${rasa.url}/webhooks/rest/webhook
  model-upload-path: /rasa-models/
  project-path: ./Chatbot_USTHB_Github/

app:
  upload:
    dir: uploads/rasa-models
    max-file-size: 100MB
    max-request-size: 100MB

llama:
  url: ${LLAMA_URL:http://localhost:5000}

# Swagger Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.chatbot: DEBUG
    org.springframework.security: DEBUG